name: testing partner-center-api before pull request

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - '*'

jobs:

  testing:

    runs-on: ubuntu-latest

    steps:
      - name: Getting project from main branch
        uses: "actions/checkout@v2"

      - name: installing dependencies
        run:
          npm install

      - name: running unit test
        run:
          npm run test

      - name: if fail
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{github.token}}
          script: |
            const ref = "${{github.ref}}"
            const pull_number = Number(ref.split("/")[2])
            await github.pulls.createReview({
              ...context.repo,
              pull_number,
              body:"테스트 코드를 다시 확인해주세요.",
              event: "REQUEST_CHANGES"
            })
        if: failure()
